In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
#Read Data
data = pd.read_excel('news.xlsx')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Date     5500 non-null   object
 1   Title    5500 non-null   object
 2   Summary  5047 non-null   object
 3   Body     5441 non-null   object
 4   Tag      5500 non-null   object
 5   cat      5500 non-null   object
dtypes: object(6)
memory usage: 257.9+ KB


In [4]:
data['Date'][10]

'تاریخ انتشار:\n۲۹ اسفند ۱۳۹۷ - ۱۵:۱۹'

In [5]:
data['Date'] = data['Date'].apply(lambda x: re.sub('تاریخ انتشار:\n', '', x))

In [6]:
data

Date  \
0       ۲۹ اسفند ۱۳۹۷ - ۲۰:۴۷   
1       ۲۹ اسفند ۱۳۹۷ - ۲۰:۳۷   
2     ۰۱ فروردین ۱۳۹۸ - ۱۱:۰۵   
3       ۲۹ اسفند ۱۳۹۷ - ۲۱:۰۵   
4       ۲۹ اسفند ۱۳۹۷ - ۱۸:۲۶   
...                       ...   
5495     ۰۴ بهمن ۱۳۹۷ - ۱۳:۴۳   
5496     ۰۴ بهمن ۱۳۹۷ - ۱۳:۳۴   
5497     ۰۴ بهمن ۱۳۹۷ - ۱۳:۳۱   
5498     ۰۴ بهمن ۱۳۹۷ - ۱۲:۲۹   
5499     ۰۴ بهمن ۱۳۹۷ - ۱۲:۱۹   

                                                  Title  \
0     قرار گرفتن فوتبال ساحلی ایران در سید دوم جام ج...   
1          تبریک اینستاگرامی کی روش به مناسبت عید نوروز   
2     تیم ملی فوتبال امید ایران - ترکمنستان؛ آغاز ما...   
3                        اولین تمرین پرسپولیس در سال ۹۸   
4     اسلامیان: قصدمان پرداخت نکردن پول کی روش نیست/...   
...                                                 ...   
5495  رزمایش بزرگ «اقتدار ۹۷» نیروی زمینی ارتش از فر...   
5496  کالاهای اساسی و گوشت مورد نیاز شب عید تامین می...   
5497  جمالی‌نژاد: توجه به کشاورزی شهری از عوامل تمای...   
5498  فرمانده نیروی هوایی ارتش از پایگاه شکاری شهید ...   
5499   لاریجانی درگذشت والده برادران مومنی را تسلیت گفت   

                                                Summary  \
0     در رده بندی جدید کنفدراسیون فوتبال آسیا، تیم م...   
1     سرمربی سابق تیم ملی فوتبال کشورمان با انتشار پ...   
2     تیم‌های ملی فوتبال امید ایران و ترکمنستان، فرد...   
3     اولین تمرین در سال جدید ۳ فروردین در ورزشگاه ش...   
4     عضو هیئت رئیسه فدراسیون فوتبال گفت: پول کی روش...   
...                                                 ...   
5495  فرمانده نیروی زمینی ارتش از آغاز رزمایش بزرگ ا...   
5496                                                NaN   
5497  معاون عمرانی وزیر کشور گفت: توجه به ابعاد مختل...   
5498  فرمانده نیروی هوایی ارتش به همراه معاونین این ...   
5499  رئیس مجلس شورای اسلامی درگذشت والده دبیرکل ستا...   

                                                   Body  \
0     به گزارش\nخبرنگار فوتبال و فوتسال\n\nگروه ورزش...   
1     به گزارش\nخبرنگار فوتبال و فوتسال\n\nگروه ورزش...   
2     به گزارش\nخبرنگار فوتبال و فوتسال\n\nگروه ورزش...   
3     به گزارش\nگروه ورزش باشگاه خبرنگاران جوان\n، ب...   
4     به گزارش\nخبرنگار فوتبال و فوتسال\n\nگروه ورزش...   
...                                                 ...   
5495  به گزارش\nحوزه دفاعی امنیتی\nگروه سیاسی باشگاه...   
5496  معاون اول رئیس جمهور با اشاره به اهتمام دولت ب...   
5497  به گزارش\nحوزه دولت\n\nگروه سیاسی باشگاه خبرنگ...   
5498  به گزارش\nحوزه دفاعی امنیتی\nگروه سیاسی باشگاه...   
5499  به گزارش\nحوزه مجلس\nگروه سیاسی باشگاه خبرنگار...   

                                                    Tag        cat  
0                       فدراسیون فوتبال\n،\nاخبار ورزشی     sports  
1      تیم ملی فوتبال\n،\nکارلوس کی روش\n،\nاخبار ورزشی     sports  
2                       اخبار ورزشی\n،\nفدراسیون فوتبال     sports  
3                       باشگاه پرسپولیس\n،\nاخبار ورزشی     sports  
4     تیم ملی فوتبال ایران\n،\nاخبار ورزشی\n،\nکارلو...     sports  
...                                                 ...        ...  
5495                               اخبار سیاسی\n،\nارتش  political  
5496      اخبار سیاسی\n،\nاسحاق جهانگیری\n،\nبانک مرکزی  political  
5497                         اخبار سیاسی\n،\nوزارت کشور  political  
5498                               اخبار سیاسی\n،\nارتش  political  
5499                       اخبار سیاسی\n،\nعلی لاریجانی  political  

[5500 rows x 6 columns]

In [7]:
data['month'] = data['Date'].apply(lambda x: x.split()[1])

In [8]:
data['month'].value_counts()

اسفند       3690
بهمن        1272
فروردین      516
اردیبهشت      18
خرداد          3
تیر            1
Name: month, dtype: int64

In [9]:
def convert_to_num(month):
    if month == 'فروردین':
        return 1
    elif month == 'اردیبهشت':
        return 2
    elif month == 'خرداد':
        return 3
    elif month == 'تیر':
        return 4
    elif month == 'بهمن':
        return 11
    elif month == 'اسفند':
        return 12
    else:
        return 'unkhonwn'

In [10]:
data['month'] = data['month'].apply(convert_to_num)

In [11]:
data

Date  \
0       ۲۹ اسفند ۱۳۹۷ - ۲۰:۴۷   
1       ۲۹ اسفند ۱۳۹۷ - ۲۰:۳۷   
2     ۰۱ فروردین ۱۳۹۸ - ۱۱:۰۵   
3       ۲۹ اسفند ۱۳۹۷ - ۲۱:۰۵   
4       ۲۹ اسفند ۱۳۹۷ - ۱۸:۲۶   
...                       ...   
5495     ۰۴ بهمن ۱۳۹۷ - ۱۳:۴۳   
5496     ۰۴ بهمن ۱۳۹۷ - ۱۳:۳۴   
5497     ۰۴ بهمن ۱۳۹۷ - ۱۳:۳۱   
5498     ۰۴ بهمن ۱۳۹۷ - ۱۲:۲۹   
5499     ۰۴ بهمن ۱۳۹۷ - ۱۲:۱۹   

                                                  Title  \
0     قرار گرفتن فوتبال ساحلی ایران در سید دوم جام ج...   
1          تبریک اینستاگرامی کی روش به مناسبت عید نوروز   
2     تیم ملی فوتبال امید ایران - ترکمنستان؛ آغاز ما...   
3                        اولین تمرین پرسپولیس در سال ۹۸   
4     اسلامیان: قصدمان پرداخت نکردن پول کی روش نیست/...   
...                                                 ...   
5495  رزمایش بزرگ «اقتدار ۹۷» نیروی زمینی ارتش از فر...   
5496  کالاهای اساسی و گوشت مورد نیاز شب عید تامین می...   
5497  جمالی‌نژاد: توجه به کشاورزی شهری از عوامل تمای...   
5498  فرمانده نیروی هوایی ارتش از پایگاه شکاری شهید ...   
5499   لاریجانی درگذشت والده برادران مومنی را تسلیت گفت   

                                                Summary  \
0     در رده بندی جدید کنفدراسیون فوتبال آسیا، تیم م...   
1     سرمربی سابق تیم ملی فوتبال کشورمان با انتشار پ...   
2     تیم‌های ملی فوتبال امید ایران و ترکمنستان، فرد...   
3     اولین تمرین در سال جدید ۳ فروردین در ورزشگاه ش...   
4     عضو هیئت رئیسه فدراسیون فوتبال گفت: پول کی روش...   
...                                                 ...   
5495  فرمانده نیروی زمینی ارتش از آغاز رزمایش بزرگ ا...   
5496                                                NaN   
5497  معاون عمرانی وزیر کشور گفت: توجه به ابعاد مختل...   
5498  فرمانده نیروی هوایی ارتش به همراه معاونین این ...   
5499  رئیس مجلس شورای اسلامی درگذشت والده دبیرکل ستا...   

                                                   Body  \
0     به گزارش\nخبرنگار فوتبال و فوتسال\n\nگروه ورزش...   
1     به گزارش\nخبرنگار فوتبال و فوتسال\n\nگروه ورزش...   
2     به گزارش\nخبرنگار فوتبال و فوتسال\n\nگروه ورزش...   
3     به گزارش\nگروه ورزش باشگاه خبرنگاران جوان\n، ب...   
4     به گزارش\nخبرنگار فوتبال و فوتسال\n\nگروه ورزش...   
...                                                 ...   
5495  به گزارش\nحوزه دفاعی امنیتی\nگروه سیاسی باشگاه...   
5496  معاون اول رئیس جمهور با اشاره به اهتمام دولت ب...   
5497  به گزارش\nحوزه دولت\n\nگروه سیاسی باشگاه خبرنگ...   
5498  به گزارش\nحوزه دفاعی امنیتی\nگروه سیاسی باشگاه...   
5499  به گزارش\nحوزه مجلس\nگروه سیاسی باشگاه خبرنگار...   

                                                    Tag        cat  month  
0                       فدراسیون فوتبال\n،\nاخبار ورزشی     sports     12  
1      تیم ملی فوتبال\n،\nکارلوس کی روش\n،\nاخبار ورزشی     sports     12  
2                       اخبار ورزشی\n،\nفدراسیون فوتبال     sports      1  
3                       باشگاه پرسپولیس\n،\nاخبار ورزشی     sports     12  
4     تیم ملی فوتبال ایران\n،\nاخبار ورزشی\n،\nکارلو...     sports     12  
...                                                 ...        ...    ...  
5495                               اخبار سیاسی\n،\nارتش  political     11  
5496      اخبار سیاسی\n،\nاسحاق جهانگیری\n،\nبانک مرکزی  political     11  
5497                         اخبار سیاسی\n،\nوزارت کشور  political     11  
5498                               اخبار سیاسی\n،\nارتش  political     11  
5499                       اخبار سیاسی\n،\nعلی لاریجانی  political     11  

[5500 rows x 7 columns]

In [12]:
data['day'] = data['Date'].apply(lambda x: x.split()[0])
data['year'] = data['Date'].apply(lambda x: x.split()[2])

In [13]:
from persiantools import characters, digits

In [14]:
data['day'] = data['day'].apply(lambda x: digits.fa_to_en(x))
data['year'] = data['year'].apply(lambda x: digits.fa_to_en(x))

In [15]:
data.drop(['Date', 'Title', 'Tag', 'Summary'], axis=1, inplace=True)

In [32]:
stopword = []
file = open('stopwords.txt', encoding='UTF-8').read()
[stopword.append(x) for x in file.split()]
stopword

['\ufeff!',
 '"',
 '#',
 '%',
 '\\',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '\\\\',
 '//',
 '?',
 '@',
 '\\',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '0',
 '’',
 '«',
 '»',
 '”',
 '“',
 '′',
 '‘',
 '،',
 '\\\\',
 'و',
 'در',
 'به',
 'از',
 'که',
 'این',
 'را',
 'با',
 'است',
 'برای',
 'آن',
 'یک',
 'خود',
 'تا',
 'کرد',
 'بر',
 'هم',
 'نیز',
 'گفت',
 'می\u200cشود',
 'وی',
 'شد',
 'دارد',
 'ما',
 'اما',
 'یا',
 'شده',
 'باید',
 'هر',
 'آنها',
 'بود',
 'او',
 'دیگر',
 'دو',
 'مورد',
 'می\u200cکند',
 'شود',
 'کند',
 'وجود',
 'بین',
 'پیش',
 'شده_است',
 'پس',
 'نظر',
 'اگر',
 'همه',
 'یکی',
 'حال',
 'هستند',
 'من',
 'کنند',
 'گردد',
 'حتما',
 'سلام',
 'دلم',
 'دیدن',
 'بزنید',
 'صحبتهای',
 'عنوان',
 'معناست',
 'خبرهای',
 'شب',
 'نیست',
 'باشد',
 'چه',
 'عده\u200cای',
 'علیه\u200cالسلام',
 'باشیم',
 'فعلی',
 'صد',
 'ان',
 'انها',
 'جناب',
 'جناب\u200cاقای',
 'میشود',
 'ع

In [36]:
def remove_stopwords(text):
    text = str(text)
    filtered_tokens = [token for token in text.split() if token not in stopword]
    filtered_text = ' '.join(filtered_tokens)
    return filtered_text

In [53]:
def delete_english_word(text):
    return re.sub(r"['a-zA-Z']", '', str(text))

In [38]:
data['Body'] = data['Body'].apply(remove_stopwords)

In [49]:
def delete_number(text):
    return re.sub(r"\d+", '', str(text))

In [51]:
data['Body'] = data['Body'].apply(delete_number)

In [54]:
data['Body'] = data['Body'].apply(delete_english_word)

In [78]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer

In [73]:
from sklearn.pipeline import Pipeline

In [79]:
model = Pipeline([('vect', CountVectorizer(min_df=40)),('tfidf', TfidfTransformer())])

In [80]:
xx = model.fit_transform(data['Body'])

In [83]:
df = pd.DataFrame(xx.toarray(), columns=model.named_steps.vect.get_feature_names())

In [84]:
df

__        آب  آباد   آبادان  آبان  آبهای  آبی  آتش  آتی  آثار  ...  \
0     0.0  0.000000   0.0  0.00000   0.0    0.0  0.0  0.0  0.0   0.0  ...   
1     0.0  0.000000   0.0  0.00000   0.0    0.0  0.0  0.0  0.0   0.0  ...   
2     0.0  0.000000   0.0  0.04649   0.0    0.0  0.0  0.0  0.0   0.0  ...   
3     0.0  0.000000   0.0  0.00000   0.0    0.0  0.0  0.0  0.0   0.0  ...   
4     0.0  0.059218   0.0  0.00000   0.0    0.0  0.0  0.0  0.0   0.0  ...   
...   ...       ...   ...      ...   ...    ...  ...  ...  ...   ...  ...   
5495  0.0  0.000000   0.0  0.00000   0.0    0.0  0.0  0.0  0.0   0.0  ...   
5496  0.0  0.000000   0.0  0.00000   0.0    0.0  0.0  0.0  0.0   0.0  ...   
5497  0.0  0.000000   0.0  0.00000   0.0    0.0  0.0  0.0  0.0   0.0  ...   
5498  0.0  0.000000   0.0  0.00000   0.0    0.0  0.0  0.0  0.0   0.0  ...   
5499  0.0  0.000000   0.0  0.00000   0.0    0.0  0.0  0.0  0.0   0.0  ...   

           یمن  یورو  یوونتوس   یک  یکبار  یکسال  یکسان  یکشنبه  یکپارچه  \
0     0.000000   0.0      0.0  0.0    0.0    0.0    0.0     0.0      0.0   
1     0.000000   0.0      0.0  0.0    0.0    0.0    0.0     0.0      0.0   
2     0.039658   0.0      0.0  0.0    0.0    0.0    0.0     0.0      0.0   
3     0.000000   0.0      0.0  0.0    0.0    0.0    0.0     0.0      0.0   
4     0.000000   0.0      0.0  0.0    0.0    0.0    0.0     0.0      0.0   
...        ...   ...      ...  ...    ...    ...    ...     ...      ...   
5495  0.000000   0.0      0.0  0.0    0.0    0.0    0.0     0.0      0.0   
5496  0.000000   0.0      0.0  0.0    0.0    0.0    0.0     0.0      0.0   
5497  0.000000   0.0      0.0  0.0    0.0    0.0    0.0     0.0      0.0   
5498  0.000000   0.0      0.0  0.0    0.0    0.0    0.0     0.0      0.0   
5499  0.000000   0.0      0.0  0.0    0.0    0.0    0.0     0.0      0.0   

       یگانهای  
0     0.000000  
1     0.000000  
2     0.000000  
3     0.000000  
4     0.000000  
...        ...  
5495  0.205562  
5496  0.000000  
5497  0.000000  
5498  0.000000  
5499  0.000000  

[5500 rows x 3347 columns]

In [85]:
# Creat Model
from sklearn.cluster import KMeans

In [115]:
clu = KMeans(n_clusters=3 ,init='k-means++', n_jobs=-1)

In [116]:
clu.fit(df)

/home/hassan/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:792: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 1.0 (renaming of 0.25).
  warnings.warn("'n_jobs' was deprecated in version 0.23 and will be"


KMeans(n_clusters=3, n_jobs=-1)

In [117]:
np.unique(clu.labels_, return_counts=True)

(array([0, 1, 2], dtype=int32), array([ 939,  477, 4084]))

In [127]:
data['predict_label'] = clu.labels_

In [119]:
data['cat'].value_counts()

political    3000
comercial    1500
sports       1000
Name: cat, dtype: int64

In [120]:
data['predict_label'].value_counts()

2    4084
0     939
1     477
Name: predict_label, dtype: int64

In [129]:
dic = {
    1: 'economic',
    0: 'sport',
    2: 'political'
    
}

In [130]:
data['predict_label'] = data['predict_label'].replace(dic)

In [131]:
data

Body        cat  month day  \
0     گزارش خبرنگار فوتبال فوتسال گروه ورزشی باشگاه ...     sports     12  29   
1     گزارش خبرنگار فوتبال فوتسال گروه ورزشی باشگاه ...     sports     12  29   
2     گزارش خبرنگار فوتبال فوتسال گروه ورزشی باشگاه ...     sports      1  01   
3     گزارش گروه ورزش باشگاه خبرنگاران جوان اساس برن...     sports     12  29   
4     گزارش خبرنگار فوتبال فوتسال گروه ورزشی باشگاه ...     sports     12  29   
...                                                 ...        ...    ...  ..   
5495  گزارش حوزه دفاعی امنیتی گروه سیاسی باشگاه خبرن...  political     11  04   
5496  معاون رئیس جمهور اهتمام دولت تامین کالاهای اسا...  political     11  04   
5497  گزارش حوزه دولت گروه سیاسی باشگاه خبرنگاران جو...  political     11  04   
5498  گزارش حوزه دفاعی امنیتی گروه سیاسی باشگاه خبرن...  political     11  04   
5499  گزارش حوزه مجلس گروه سیاسی باشگاه خبرنگاران جو...  political     11  04   

      year predict_label  
0     1397         sport  
1     1397         sport  
2     1398         sport  
3     1397         sport  
4     1397         sport  
...    ...           ...  
5495  1397     political  
5496  1397     political  
5497  1397     political  
5498  1397     political  
5499  1397     political  

[5500 rows x 6 columns]

In [169]:
data['predict_label'].value_counts()

political    4084
sport         939
economic      477
Name: predict_label, dtype: int64

In [170]:
from sklearn.metrics import silhouette_score
silhouette_score(df, clu.labels_)

0.02808607204848944

In [176]:
text = '''در پایان جام زیلکوفسکی لهستان و مشخص شدن نتایج آزادکاران ایران در ۳ وزن المپیکی ۷۴، ۹۷ و ۱۲۵ کیلوگرم، ۶ آزادکار ایران در المپیک توکیو مشخص شدند.

به گزارش ایسنا، رقابت های بین المللی کشتی آزاد جام زیلکوفسکی لهستان به پایان رسید و نمایندگان اوزان ۷۴، ۹۷ و۱۲۵ کیلوگرم ایران در المپیک توکیو تقریبا مشخص شدند.
کادر فنی تیم ملی کشتی آزاد با هدف نهایی کردن ترکیب تیم ملی در المپیک، یونس امامی و مصطفی حسین خانی در وزن ۷۴ کیلوگرم، علیرضا کریمی، علی شعبانی و محمدحسین محمدیان در ۹۷ کیلوگرم و امین طاهری و امیرحسین زارع در ۱۲۵ کیلوگرم را عازم این رقابت ها کرد تا در نهایت با مشخص شدن ۳ نماینده ایران در المپیک توکیو، پرونده انتخابی تیم ملی کشتی آزاد برای حضور در این رقابت ها بسته شود.
'''


In [178]:
simple = model.transform([text]).toarray()

In [179]:
clu.predict(simple)

array([0], dtype=int32)

In [180]:
text1 = '''
سخنگوی وزارت خارجه آمریکا در واکنش به ورود ناوهای نظامی ایران به اقیانوس اطلس گفت: اگر هدف ارسال سلاح به عوامل نیابتی جمهوری اسلامی ایران در منطقه باشد، آمریکا آماده است واکنش نشان دهد.

به گزارش ایسنا، ند پرایس در نشست خبری روزانه خود و در پاسخ به پرسشی درباره ورود ناوگروه ایرانی به اقیانوس اطلس و حرکت به سوی قاره آمریکا این زمینه گفت: ما آماده‌ایم از اختیارات قابل استفاده خود، از جمله تحریم‌ها، علیه هر عاملی که ایران را قادر می‌سازد به تامین سلاح برای عوامل خشن و نیابتی‌اش ادامه دهد استفاده کنیم
'''

In [181]:
simple1 = model.transform([text1]).toarray()

In [182]:
clu.predict(simple1)

array([2], dtype=int32)

### Balance The Label And  Then Predict The Model
## Important Question Why The Model It's Not Be Better Than The old One

In [189]:
from imblearn.combine import SMOTETomek

In [190]:
smt = SMOTETomek(random_state=42)
X_res, y_res = smt.fit_resample(df, data['cat'])

In [194]:
np.unique(y_res, return_counts=True)

(array(['comercial', 'political', 'sports'], dtype=object),
 array([2997, 2997, 3000]))

In [195]:
clu_balance = KMeans(n_clusters=3 ,init='k-means++', n_jobs=-1)

In [196]:
clu_balance.fit(X_res)

/home/hassan/.local/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:792: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 1.0 (renaming of 0.25).
  warnings.warn("'n_jobs' was deprecated in version 0.23 and will be"


KMeans(n_clusters=3, n_jobs=-1)

In [197]:
np.unique(clu_balance.labels_, return_counts=True)

(array([0, 1, 2], dtype=int32), array([5964,  575, 2455]))